## This file helps with adding the requirements for the CMakelists



def include_directory(dir_list): # Adds all Install directories
    all_directories = ' '.join(dir_list)
    appended_directories = f"install(\n\tDIRECTORY\n\t{all_directories}\n\tDESTINATION share/${{PROJECT_NAME}}\n)\n"
    return appended_directories

def include_scripts(script_list): # Adds all Install programs
    all_scripts = '\n\t'.join(script_list)
    appended_scripts = f"install(\n\tPROGRAMS\n\t{all_scripts}\n\tDESTINATION lib/${{PROJECT_NAME}}\n)\n" # Add the Python Scripts under this after making them exe
    return appended_scripts

def include_env_hooks():
    appended_hooks = 'ament_environment_hooks("${CMAKE_CURRENT_SOURCE_DIR}/env-hooks/${PROJECT_NAME}.sh.in")'
    return appended_hooks

def appender(dir_list,script_list): 
    Cmake_dir = include_directory(dir_list)
    Cmake_script = include_scripts(script_list)
    Cmake_hooks = include_env_hooks()
    with open('CMakeLists.txt','r') as file:
        lines = file.readlines()
    
    if lines:
        lines = lines[:-1]

    with open('CMakeLists.txt','w') as file: #Make sure that the previous funcs dir points to pkg
        file.writelines(lines)
        file.write("# ***** CMAKE FILE GENERATED BY ROS_AUTOGEN*****")
        file.write('\n')
        file.write(Cmake_hooks)
        file.write("\n")
        file.write("ament_package()")
        file.write("\n")
        file.write(Cmake_dir)
        file.write('\n')
        file.write(Cmake_script)
        file.write('\n')

