## This file helps with adding the requirements for the CMakelists



def include_directory(dir_list): # Adds all Install directories
    all_directories = ' '.join(dir_list)
    appended_directories = f"install(\n\tDIRECTORY\n\t{all_directories}\n\tDESTINATION share/${{PROJECT_NAME}}\n)\n"
    return appended_directories

def include_scripts(script_list): # Adds all Install programs
    all_scripts = '\n\t'.join(script_list)
    appended_scripts = f"install(\n\tPROGRAMS\n\t{all_scripts}\n\tDESTINATION share/${{PROJECT_NAME}}\n)\n"
    return appended_scripts

def appender(dir_list,script_list,mesh_include): 
    Cmake_dir = include_directory(dir_list)
    Cmake_script = include_scripts(script_list)
    with open('CMakeLists.txt','a') as file: #Make sure that the previous funcs dir points to pkg
        file.write("# ***** CMAKE FILE GENERATED BY AUTOMATON*****")
        file.write("\n")
        file.write(Cmake_dir)
        file.write('\n')
        file.write(Cmake_script)

